# Stop and purge any conflicting installs
- name: Stop docker service if present
  service: { name: docker, state: stopped }
  ignore_errors: yes

- name: Stop docker.socket if present
  service: { name: docker.socket, state: stopped }
  ignore_errors: yes

- name: Purge conflicting docker packages
  apt:
    name:
      - docker.io
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: absent
    purge: yes
    force_apt_get: yes
    lock_timeout: 600

- name: Autoremove leftovers
  apt:
    autoremove: yes
    purge: yes
    force_apt_get: yes
    lock_timeout: 600

# Fresh install from Docker's official repo
- name: Ensure base deps and keyrings dir
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
    force_apt_get: yes
    lock_timeout: 600

- name: Create /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  shell: |
    set -e
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker APT repo (stable)
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: apt update after adding Docker repo
  apt:
    update_cache: yes
    force_apt_get: yes
    lock_timeout: 600

# Ensure overlay2 modules available
- name: Install kernel extra modules for current kernel (ok if already present)
  apt:
    name: "linux-modules-extra-{{ ansible_kernel }}"
    state: present
    force_apt_get: yes
    lock_timeout: 600
  register: extra_mods
  failed_when: false

- name: Install Docker Engine and Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    force_apt_get: yes
    lock_timeout: 600

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start docker.socket
  service:
    name: docker.socket
    state: started
    enabled: yes

- name: Enable and start docker service
  service:
    name: docker
    state: started
    enabled: yes

